version: '1'
services:
  jupyter-notebook:
    build: base-notebook
    container_name: jupyter-notebook
    ports:
      - ${JUPYTER_PORT}:8888
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./base-notebook/work:/home/jovyan/work
    command: ["start-notebook.sh", "--NotebookApp.token=''"]
  pgsql:
    image: postgres:15
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432