CREATE TABLE "writer_list" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "writer_name" varchar
);

CREATE TABLE "category_list" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar
);

CREATE TABLE "book_list" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "book_name" varchar(128),
  "writer_id" integer,
  "category_id" integer
);

CREATE TABLE "book_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" integer,
  "book_id" integer,
  "price" integer,
  "user_rating" float,
  "reviews" integer
);

CREATE UNIQUE INDEX ON "writer_list" ("writer_name");

CREATE UNIQUE INDEX ON "category_list" ("category_name");

CREATE UNIQUE INDEX ON "book_list" ("book_name");

CREATE UNIQUE INDEX ON "book_reviews" ("year", "book_id", "price");

COMMENT ON TABLE "writer_list" IS 'information of writer';

COMMENT ON COLUMN "writer_list"."id" IS 'Id of Author';

COMMENT ON COLUMN "writer_list"."writer_name" IS 'Name of Author';

COMMENT ON TABLE "category_list" IS 'information of category';

COMMENT ON COLUMN "category_list"."id" IS 'Id of Category';

COMMENT ON COLUMN "category_list"."category_name" IS 'Name of Category';

COMMENT ON TABLE "book_list" IS 'information of book';

COMMENT ON COLUMN "book_list"."id" IS 'Id of Book';

COMMENT ON COLUMN "book_list"."book_name" IS 'Name of Book';

COMMENT ON COLUMN "book_list"."writer_id" IS 'Writer id of Book';

COMMENT ON COLUMN "book_list"."category_id" IS 'Category id of Book';

COMMENT ON TABLE "book_reviews" IS 'information of book review';

COMMENT ON COLUMN "book_reviews"."id" IS 'id of Book Review';

COMMENT ON COLUMN "book_reviews"."year" IS 'year of Book Review';

COMMENT ON COLUMN "book_reviews"."book_id" IS 'Id of Book';

COMMENT ON COLUMN "book_reviews"."price" IS 'price of Book';

COMMENT ON COLUMN "book_reviews"."user_rating" IS 'rating of Book Review by user';

COMMENT ON COLUMN "book_reviews"."reviews" IS 'number of user who give rating';

ALTER TABLE "book_list" ADD FOREIGN KEY ("writer_id") REFERENCES "writer_list" ("id");

ALTER TABLE "book_list" ADD FOREIGN KEY ("category_id") REFERENCES "category_list" ("id");

ALTER TABLE "book_reviews" ADD FOREIGN KEY ("book_id") REFERENCES "book_list" ("id");
